sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: oVr6cCDiXpkmLPSzqG6DtrV9gwzB8+Fl9COEaPnCKkTukx0zHtBzUqtf/Vsm21QkEk6VtxPmPvZQkQxCL35fV/8AlBiRBhx9eDMWaB+BQjR8+U0ovz8f5uEx6RwjTsZf8yEVxd1k11AdOdVM+sI/+wKtuZvue1L0WaWQyO+Nf4OweScShzYXW98M/KbZdhkcL5iZ0Xe8r0bvhxbpWoTE4L3aoI14kZkFKixRRKoP2J+DveUSByIa/WDdOfpRcg/UMDwE9hJYqvFtlTs9Iu6j9JSNOTB6LUvm2S8FNbBM6R/+t3P8htFCHNvP+lxga6G8Ght0hRm+vqVmOBOnaDiCJ3NTgA6wRtUCVJ27ljFM2zg8Ro2P12pcTxehpU3t/hKMeI36UbHCoe+442ZAoZugTpgJYFhR0nWRSrdQmTkL038h82ZUw1FdGkL0fn5yH3cGmIz41VsCHps37TCccf//sbM4RvE30/ANUXzSvq11bKpy5DXSR+jBE7xBPMs22MFOYVr4PTRtTurhYO4lokpBM7ePcoLF6X0pHJ5endLxd682+033UVqZQ/mfXBh96KMb7dqQ9+fQhxKGTB2uWBmcQAhDCcRajThPJrPwLPxPcGHBYLbWqfMnKX8okz3LiIFB799nkBX1np7RuCT9ccZ+jkNYLujXrErSDlfkDIumtQ8=
  - secure: 2UZzMQ5Gf5tTRwo7x0SuVdyLxaTvNcv9TXLWJC355cXPnxULQGOSp+chLbFOlcoXEt6+tKjr8R6IGxUMBGGva5PV8jabEAzWBiqKNH+A9lSSw0YRi5QQk61AlWfjl91pt/OFO/tPOvQTThrQwO38lj1Z4NG7BpTxS8k7XVEtfXULb6gTOvyyh6YbyYIrvGTOtdoZKAJA3vJlHY3vNe8QhxB4jOiLEGpfd7HGhInq1l6r4GQoJCdg4T7IuIQQmSYftHK/kjoLIvCaHxaq2YuCVXDrcXdfHpCYkmIPA/IKsERpcVcVLr+8nEKFmm5ETKQUuAeJynqVnFeXKHuymXSCiioLJVlyXKCeXxr4/4s+vMSl0okvHVV3ENSGmxxsG1aNHEWmH7CO45dSxdddH49JW5eFeZkAckb3RL2cLggSQZbI1Igu1VBabZbZBzrp1/uN3Qn3PmEuRrvOuPyA28c3LdEMQo8yFbBxO1ThVQyFWy4ZN4O6zKWr26T3vY9XzCWgxm4RRllVUXot4b5Mih+ZPAHv3gD40XlgJWrg3rWLJ5wKflBcUgBntwBKaK25eAVOfUwLEnhHSDTlaB+qiEp3mJHI6I76E5yUBNxpIsEW+i3KJ2FZWGOKM1kFdvqXlhswDR1cOtsxrS7vC23fJMbHDIXIQRe70ICmilSwRUY/vLY=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: kg4XODkzCwiZ+fi57UsUm5GDZ6eoABU2Y6KvPfF8qL7Uzx8cm4Jc0d+MTiYijmOrpE8Oz32vHeHPV3c3ug4KEFplLseXt2MALOW4iDGukVWPutlKzOsCEXTMUGV13DqCgyzkZdrkao8kL0aj3Wcgpf0fmA0i+AWupJIbU/aHefET0QsxBQ21mq6f9BPAHk05JpzBRz1kYdrWzXIK8bEDI/0VkQnatEOnIsr8VQf4WLuSOMF3RWiWpNyLY3jx9qdWNjh9SZKWfpf7PGgBQi27bpef7CmBaXbeO/08b3QcWlFcdKJ8jZKAidZb1iVXPoGc7jd5QwlR2OX6xJkrViK5fXMTGqYhXWdhZ7OLwl18Y/ydlncPgPCNtcchhRtT+ROw07HMEZT9u40GSHyKeEG+9n45Cr4o8fccCXHSGmf43RrIuRhU1HVP+rEl3P+b+SSRhWXGe2LP/UQikBVk5dShi2n2B94C4k/pS4v+cH3jofNOxJN7mM4RsF110tdEtXPhhyzIdy1RgtQ0lWWm5qYjBF5+HOFryg0RlTuOOD9r48yzFykGuIfqAV50SdvCHpJvKQnCNG9l65BCQc6Q0XBYeyIKHlNLC5WtGdmTID71psgoEGsC5F+mt5asCfuxd79dcL8OUVVP5Z609jpJfsrkOwfd6MLlpvSvsu6vG0I8/+Q=
